//GET http://ergast.com/api/f1/drivers/zhou/constructors.json
#GET https://media.formula1.com/image/upload/f_auto/q_auto/v1677244985/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png.transform/7col/image.png
#GET https://www.formula1.com/en/racing/2023/Miami/Circuit.html
GET http://ergast.com/api/f1/2024/2/results.json
//GET http://ergast.com/api/f1/2023/drivers.json
//GET https://restcountries.com/v3.1/demonym/Dutch
#GET http://ergast.com/api/f1/2023/4/results.json
#GET https://ergast.com/api/f1/2023.json
#GET http://ergast.com/api/f1/2023/22/results.json
#GET https://ergast.com/api/f1/2023/circuits.json